name: Snowflake CI/CD Pipeline

on:
  push:
    branches:
        - dev
        - qa
        - pre-prod
        - prod
        
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev, qa, pre_prod, prod)'
        required: true
        default: dev

jobs:
  deploy:
    runs-on: github-aks-arc-runners-dev-1
    environment: ${{ github.event.inputs.environment || github.ref_name }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name : Set ENV Variable based on Branch
      run: echo "DEPLOY_ENV= ${{github.event.inputs.environment || github.ref_name}}" >> $GITHUB_ENV

    - name: Install Python and pip (Ubuntu/Debian)
      run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip 

    - name: Verify Python and pip installation
      run: |
          python3 --version
          pip3 --version
          which pip
          python3 -m pip install snowflake-cli
          which snow
          snow --version

    - name: SNOWFLAKE CLI INSTALLATION
      uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
          cli-version: "latest"
          default-config-file-path:
              ${{github.workspace}}/config/config.toml

    # - name: TEST SNOW CLI CONNECTION
    #   env:
    #     SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ vars.SNOWFLAKE_USER }}
    #     SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
    #     SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ vars.SNOWFLAKE_PASSWORD }}
    #   run: |
    #     snow --version
    #     snow connection test 


    # - name: Install snow-cli
    #   run: |
    #       python3 -m pip install snowflake-cli

    # - name: Install Dependencies
    #   run: |
    #     python3 -m pip install --no-cache-dir --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org snowflake-connector-python

    # - name: INSTALL SNOWFLAKE CLI
    #   run: |
    #     curl  -fsSL https://raw.githubusercontent.com/Snowflake-Labs/snowflake-cli/main/install.sh |bash
    #     export PATH=$HOME/.snowflake/bin:$PATH
    #     snow --version
        
    # - name: Deploy to Snowflake
    #   run: bash deploymentScript/deploy.sh
    #   env:
    #     SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
    #     SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
    #     SNOWFLAKE_PASSWORD: ${{ vars.SNOWFLAKE_PASSWORD }}
    #     SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
    #     SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
    #     TARGET_ENV: ${{ github.event.inputs.environment }}