[connections.default]
# Your Snowflake account identifier (e.g., xy12345.east-us-2.azure)
account = "bummqfk-te56281"

# Credentials for Snowflake authentication
user = "SJAIN"
password = "SNOW@SankalpJ30"  # For security, consider using environment variables

# Optional: Specify the role, warehouse, database, and schema to use by default
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SNOWFLAKE_SAMPLE_DATA"
schema = "TPCH_SF1"

[logging]
level = "info"
